### ISSUE TITLE
cannot import?

### ISSUE THREAD

**Issue by NCrusher74** [Phisto/TagLib#2]
Hi, I've only been coding for about six months, and I'm desperately seeking a framework or SPM package I can use in a Swift project for tagging audiobook files, and I'm trying to give your framework a testdrive to see if I can make it work, but even though I've added it to my project as a framework and linked the library and created the Git submodule, when I try to use `import TagLib`, XCode acts like it's never heard of TagLib, even though I just watched it index the files and build without error.

Do you know why I might be experiencing this?

**Comment by Phisto** [comment]
hey crusher,
i added a module map, but im not sure if that was the cause of your problem.
does the debugger say something? maybe a signing issue?

i dont know nothing about swift development, but i tried to use the framework in a blank xcode swift project and it worked (that was after i added module support to the framework though)

**Comment by NCrusher74** [comment]
Thank you! I will take it for a spin and see what I can do with it!

**Comment by NCrusher74** [comment]
Hmm. Well, when importing it, it says "could not build ObjectiveC module.

Ah well, thanks for trying!

**Comment by NCrusher74** [comment]
Hi! I actually did get this to work eventually. Turns out I was still missing ObjC wrappers in order for Swift to play nice with the C++.

I borrowed the wrappers from [TagLibIOS](https://github.com/NCrusher74/TagLibIOS) (which I hadn't wanted to use because I hate the way CocoaPods takes over a project and leaves it feeling all cluttered with stuff--case in point, the fact that I couldn't strip the CocoaPods stuff out of TagLibIOS)  and I'm presently working on adding one for MP4 as well as the existing wrappers for MP3/Flac/AIFF. 

You can see the result [here](https://github.com/NCrusher74/TagLib/tree/mp4-wrapping) and if you want me to do a RP when I'm sure it's working, I will. I just need to figure out the image writing for the MP4 wrapper. I don't actually know Objective-C, I just started learning Swift a few months ago. I managed to monkey-see/monkey-do most of what I've done so far by imitating the other wrappers but the want MP4 handles images is different enough from the way the other ones do that I can't get away with it there.

Thanks again!

**Comment by Phisto** [comment]
Thats nice to hear! I wanted to start using swift in the course of this year so maybe i will have a more thorough look into swift integration of taglib, i guess your work will help me there, so thanks :)

But i would suggest that you create a new library (something like TagLibKit) to seperate the TagLib code from your wrapper code. I did this here: [AudioFileTagger](https://github.com/Phisto/AudioFileTagger) though its only for MP3 file tagging. Tagib is an old (in the sense of long running) open source project where a lot of people put a lot of effort into and i wouldnt feel comfortable that people could confuse my work with the work of those people :)

**Comment by NCrusher74** [comment]
Good point. I will do that!

**Comment by NCrusher74** [comment]
LOL I think your AudioBook tagger project is the sort of thing I've been looking for all along, except that I need something that will support a wider ranger of frames, including CHAP, CTOC, and TXXX frames.
